# Generated by Django 5.2.13 on 2026-05-03 14:29

import django_mongodb_backend.fields.auto
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(max_length=10)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('summary', models.JSONField()),
                ('social', models.JSONField()),
                ('sensory', models.JSONField()),
                ('support', models.JSONField()),
                ('raw_data', models.JSONField()),
                ('metadata', models.JSONField()),
                ('assessment_completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
