# Generated by Django 5.2.13 on 2026-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sensory',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='support',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='version',
        ),
        migrations.AddField(
            model_name='profile',
            name='sensory_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_analysis',
            field=models.JSONField(default=dict),
        ),
    ]
