# Generated by Django 5.2.13 on 2026-05-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
