# Generated by Django 5.2.13 on 2026-05-23 11:59

import django.core.validators
import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breathing', 'Breathing'), ('meditation', 'Meditation'), ('sleep', 'Sleep'), ('relaxation', 'Relaxation'), ('focus', 'Focus'), ('anxiety_relief', 'Anxiety relief')], max_length=30)),
                ('time_takes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('emoji', models.CharField(max_length=8)),
                ('steps', models.JSONField(default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='activities__categor_036116_idx'), models.Index(fields=['is_deleted'], name='activities__is_dele_e3af1d_idx'), models.Index(fields=['created_at'], name='activities__created_0e5d3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityRating',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='activities.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['activity', 'created_at'], name='activities__activit_c4e4fe_idx'), models.Index(fields=['user', 'created_at'], name='activities__user_id_abc2a7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'activity'), name='unique_user_activity_rating')],
            },
        ),
    ]
