# Generated by Django 5.2.13 on 2026-05-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation_runs', '0002_alter_recommendationrun_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendationrun',
            name='profile',
        ),
    ]
